# Generated by Django 3.2.14 on 2022-08-15 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_customuser_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='middle_name',
        ),
    ]
