# Generated by Django 3.2.14 on 2022-08-15 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_customuser_middle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_id',
            field=models.CharField(default='FKS533F7C5', max_length=10, unique=True),
        ),
    ]
