# Generated by Django 3.2.14 on 2022-08-15 15:09

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_customuser_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_id',
            field=models.CharField(default=core.models.generate_user_id, max_length=10, null=True, unique=True),
        ),
    ]
