# Generated by Django 3.2.14 on 2022-08-23 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_customuser_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(blank=True, null=True, upload_to='food_images/')),
                ('category', models.CharField(choices=[('ASIAN', 'ASIAN'), ('CHINESE', 'CHINESE'), ('ITALIAN', 'ITALIAN'), ('MEXICAN', 'MEXICAN'), ('HAMBURGER', 'HAMBURGER')], default='ASIAN', max_length=10)),
                ('sub_category', models.CharField(choices=[('VEG', 'VEG'), ('NON_VEG', 'NON_VEG')], default='VEG', max_length=10)),
                ('price', models.FloatField(max_length=10)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=350)),
                ('phone_number', models.CharField(max_length=12, unique=True)),
                ('availability', models.BooleanField(default=True)),
                ('reviews', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.food')),
            ],
        ),
    ]
