# Generated by Django 3.2.14 on 2022-08-28 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_food_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='food',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='food',
            field=models.ManyToManyField(to='core.Food'),
        ),
    ]
