# Generated by Django 3.2.14 on 2022-08-28 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20220828_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='food',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='foods',
            field=models.ManyToManyField(blank=True, to='core.Food'),
        ),
    ]
