# Generated by Django 3.2.14 on 2022-09-12 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_review_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='key',
            field=models.CharField(max_length=5, null=True, unique=True),
        ),
    ]
