# Generated by Django 3.2.14 on 2022-09-12 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_restaurant_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='key',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
