# Generated by Django 3.2.14 on 2022-09-16 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_restaurant_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='restaurant',
        ),
        migrations.AddField(
            model_name='review',
            name='restaurant',
            field=models.ManyToManyField(blank=True, to='core.Restaurant'),
        ),
    ]
